sudo: required
language: c

env:
  global:
    - BROKENDNS=1

install:
- sudo apt-get update -qq
- sudo apt-get install -y python-flask doxygen valgrind libpcap-dev python-pip cmake
  build-essential pkg-config libglib2.0-dev resource-agents python-gi python-netaddr
  python-demjson
- sudo -H pip install --upgrade pip
- sudo -H pip install ctypesgen testify flask getent py2neo
before_script:
- wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.1.tar.gz
- tar xvfz libsodium-1.0.1.tar.gz
- cd libsodium*
- "./configure"
- make && make check && sudo make install
- sudo ldconfig
services:
- neo4j
script:
- cd $TRAVIS_BUILD_DIR
- cd ..
- mkdir root_of_binary_tree
- cd root_of_binary_tree
- cmake $TRAVIS_BUILD_DIR
- sudo make install
- sudo ldconfig /usr/lib/x86_64-linux-gnu/assimilation
- sudo cpack
- sudo dpkg -i *.deb
- sudo /etc/init.d/nanoprobe stop
- sudo /etc/init.d/cma stop
- sudo assimcli genkeys
- cd $TRAVIS_BUILD_DIR/cma
- testify -v tests
- $TRAVIS_BUILD_DIR/discovery_agents/netconfig
- cd $TRAVIS_BUILD_DIR
- cd ../root_of_binary_tree/testcode/pinger ::1
